apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: app-container
    image: my-app:latest
    ports:
    - containerPort: 8080
  - name: sidecar-container
    image: log-collector:latest
    args: ["--log-path=/var/log/app"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/app
  volumes:
  - name: shared-logs
    emptyDir: {}
