apiVersion: v1
kind: Pod
metadata:
  name: pod-with-env
spec:
  containers:
  - name: app-container
    image: my-app:latest
    env:
    - name: ENVIRONMENT
      value: production
    - name: DEBUG
      value: "false"
