apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html" #Mounts the PVC (my-pvc) at /usr/share/nginx/html inside the container.
      name: my-storage
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        memory: "512Mi"
        cpu: "500m"
  volumes:                                   #Links the volume to the PVC.
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc