apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data
    server: 192.168.1.100 #IP address of NFS server
  persistentVolumeReclaimPolicy: Retain